export interface shipType {
  name: string
  creation: string
  modified: string
  modified_by: string
  owner: string
  docstatus: number
  idx: number
  sender: string
  origin_area: any
  origin_city: string
  sender_phone: any
  sender_name: string
  origin_adress_line_1: any
  origin_country: string
  sender_address: any
  origin_address_line2: any
  origin_state: string
  consignee: string
  destination_area: any
  destination_city: string
  consignee_phone: any
  consignee_name: any
  destination_address_line_1: any
  destination_country: string
  consignee_address: any
  destination_address_line_2: any
  destination_state: string
  origin_zone: string
  destination_zone: string
  service: any
  total_weight: number
  status: string
  movable_units: any
  amended_from: any
  company: string
  cod: number
  total_cod: number
  barcode: string
  branch: any
  currency: string
  pieces: number
  not_available: number
  percentage: number
  total_fees: number
  awb_terms_template: any
  awb_terms_and_conditions: any
  sales_invoice_created: number
  _user_tags: any
  _comments: any
  _assign: any
  _liked_by: any
  geolocation_evkp: any
  shipping_service: string
  delivery_time: any
  from_client_side: number
  destination_branch: any
  origin_branch: any
  delivery_due_date: any
  company_currency: string
  exchange_rate: number
  overdue: number
  posting_date: string
  posting_time: string
  is_returned: number
  custodian: any
  assignee: any
  closed: number
  custodian_commission: number
  awb_date: string
  type: any
  origin_address_line_1: any
  service_type: any
  adjusted_cod: number
}
